language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
env:
  - HOST=localhost DATABASE=postgres USER=postgres PASSWORD=postgres
services:
  - postgresql
before_script:
- psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
- psql -c "CREATE DATABASE test_postgres;" -U postgres
# command to run tests
script:
  - python create_tables.py
  - nosetests --with-coverage
#run coverage tests
after_success:
  - coveralls
